services:
  dds-postgres:
    image: postgres:9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ds2
      POSTGRES_USER: ds2
      POSTGRES_PASSWORD: ds2
    volumes:
      - dds-postgres_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
      - ./data_files:/data_files:ro
    networks:
      - app-network
    command: ["postgres", "-c", "log_statement=all"]
  # https://github.com/devilbox/docker-php-fpm-5.4
  dds-php:
    image: devilbox/php-fpm:5.6-prod
    volumes:
      - ./web/php:/var/www/default/htdocs
    networks:
      - app-network
    depends_on:
      - dds-postgres
  dds-nginx:
    image: devilbox/nginx-mainline
    ports:
      - "8100:81"
    volumes:
      - ./web/php:/var/www/default/htdocs
      - ./conf/nginx-legacy.conf:/etc/httpd/vhost.d/default.conf
    environment:
      PHP_FPM_ENABLE: 1
      PHP_FPM_SERVER_ADDR: php
      PHP_FPM_SERVER_PORT: 9000
    networks:
      - app-network
    depends_on:
      - dds-php

networks:
  app-network:
    driver: bridge

volumes:
  dds-postgres_data:
