services:
  dds2-nginx:
    image: devilbox/nginx-mainline
    ports:
      - "8100:81"
    volumes:
      - ./conf/nginx-hasurafied.conf:/etc/httpd/vhost.d/default.conf
    environment:
      PHP_FPM_ENABLE: 1
      PHP_FPM_SERVER_ADDR: php
      PHP_FPM_SERVER_PORT: 9000
    networks:
      - app-network
    depends_on:
      - dds2-graphql-engine
  dds2-graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "28080:8080"
    depends_on:
      - dds2-postgres
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://ds2:ds2@dds2-postgres:5432/ds2
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://ds2:ds2@dds2-postgres:5432/ds2
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret_not_for_production
    networks:
      - app-network
  dds2-postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ds2
      POSTGRES_USER: ds2
      POSTGRES_PASSWORD: ds2
    volumes:
      - dds2-postgres_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
      - ./data_files:/data_files:ro
    networks:
      - app-network
    command: ["postgres", "-c", "log_statement=all"]

networks:
  app-network:
    driver: bridge

volumes:
  dds2-postgres_data:
