
alter table if exists CUSTOMERS DISABLE TRIGGER ALL;
alter table if exists ORDERS DISABLE TRIGGER ALL;
alter table if exists ORDERLINES DISABLE TRIGGER ALL;
alter table if exists CUST_HIST DISABLE TRIGGER ALL;
alter table if exists INVENTORY DISABLE TRIGGER ALL;
alter table if exists PRODUCTS DISABLE TRIGGER ALL;

drop table IF EXISTS  INVENTORY, CUSTOMERS, ORDERS, ORDERLINES, CUST_HIST cascade;
drop table IF EXISTS PRODUCTS, CATEGORIES, REORDER cascade;

DROP TRIGGER IF EXISTS RESTOCK ON INVENTORY;

